spring:
  application:
    name: msa-zuul-server
server:
  port: 8090
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
zuul:
  routes:
    msa-user-service:
      path: /api/user/**